//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassifiedsAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlagType
    {
        public FlagType()
        {
            this.FlaggedItems = new HashSet<FlaggedItem>();
        }
    
        public int flagTypeId { get; set; }
        public string flagType1 { get; set; }
    
        public virtual ICollection<FlaggedItem> FlaggedItems { get; set; }
    }
}
