//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassifiedsAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.FlaggedItems = new HashSet<FlaggedItem>();
            this.ItemForSales = new HashSet<ItemForSale>();
            this.ItemImages = new HashSet<ItemImage>();
            this.WatchItems = new HashSet<WatchItem>();
            this.Categories = new HashSet<Category>();
            this.KeyWords = new HashSet<KeyWord>();
            this.Tags = new HashSet<Tag>();
        }
    
        public int itemId { get; set; }
        public string itemName { get; set; }
        public string itemDescription { get; set; }
        public int itemLocationZip { get; set; }
        public System.DateTime itemPostTime { get; set; }
        public double itemPrice { get; set; }
        public int listingTypeId { get; set; }
    
        public virtual ICollection<FlaggedItem> FlaggedItems { get; set; }
        public virtual ICollection<ItemForSale> ItemForSales { get; set; }
        public virtual ICollection<ItemImage> ItemImages { get; set; }
        public virtual ICollection<WatchItem> WatchItems { get; set; }
        public virtual ListingType ListingType { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<KeyWord> KeyWords { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
    }
}
