//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassifiedsAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityQuestion
    {
        public int securityQuestionId { get; set; }
        public string question { get; set; }
        public string answer { get; set; }
        public int userId { get; set; }
    
        public virtual User User { get; set; }
    }
}
