//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassifiedsAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public Tag()
        {
            this.Items = new HashSet<Item>();
        }
    
        public int tagId { get; set; }
        public string tagName { get; set; }
        public int userId { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Item> Items { get; set; }
    }
}
